/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as ReformatExcelImport } from './routes/reformat-excel'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as InsightsImport } from './routes/insights'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as ProgressJobIdImport } from './routes/progress/$jobId'
import { Route as LayoutSubmitCropImport } from './routes/_layout/submit-crop'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutOrdersImport } from './routes/_layout/orders'
import { Route as LayoutOffersImport } from './routes/_layout/offers'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutFileExplorerImport } from './routes/_layout/file-explorer'
import { Route as LayoutCustomersImport } from './routes/_layout/customers'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutToolsImageLinksImport } from './routes/_layout/tools/image-links'
import { Route as LayoutToolsGoogleImagesImport } from './routes/_layout/tools/google-images'
import { Route as LayoutToolsDataWarehouseImport } from './routes/_layout/tools/data-warehouse'
import { Route as LayoutToolsCropImport } from './routes/_layout/tools/crop'
import { Route as LayoutSubmitFormSuccessImport } from './routes/_layout/submit-form/success'
import { Route as LayoutSubmitFormOfferImport } from './routes/_layout/submit-form/offer'
import { Route as LayoutScrapingApiUserAgentsImport } from './routes/_layout/scraping-api/user-agents'
import { Route as LayoutScrapingApiGoogleSerpImport } from './routes/_layout/scraping-api/google-serp'
import { Route as LayoutScrapingApiExploreImport } from './routes/_layout/scraping-api/explore'
import { Route as LayoutScrapingApiScrapingJobsIndexImport } from './routes/_layout/scraping-api/scraping-jobs/index'
import { Route as LayoutScrapingApiScrapingJobsJobIdImport } from './routes/_layout/scraping-api/scraping-jobs/$jobId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const ReformatExcelRoute = ReformatExcelImport.update({
  id: '/reformat-excel',
  path: '/reformat-excel',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const InsightsRoute = InsightsImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const ProgressJobIdRoute = ProgressJobIdImport.update({
  id: '/progress/$jobId',
  path: '/progress/$jobId',
  getParentRoute: () => rootRoute,
} as any)

const LayoutSubmitCropRoute = LayoutSubmitCropImport.update({
  id: '/submit-crop',
  path: '/submit-crop',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutOrdersRoute = LayoutOrdersImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutOffersRoute = LayoutOffersImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutFileExplorerRoute = LayoutFileExplorerImport.update({
  id: '/file-explorer',
  path: '/file-explorer',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCustomersRoute = LayoutCustomersImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutToolsImageLinksRoute = LayoutToolsImageLinksImport.update({
  id: '/tools/image-links',
  path: '/tools/image-links',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutToolsGoogleImagesRoute = LayoutToolsGoogleImagesImport.update({
  id: '/tools/google-images',
  path: '/tools/google-images',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutToolsDataWarehouseRoute = LayoutToolsDataWarehouseImport.update({
  id: '/tools/data-warehouse',
  path: '/tools/data-warehouse',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutToolsCropRoute = LayoutToolsCropImport.update({
  id: '/tools/crop',
  path: '/tools/crop',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSubmitFormSuccessRoute = LayoutSubmitFormSuccessImport.update({
  id: '/submit-form/success',
  path: '/submit-form/success',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSubmitFormOfferRoute = LayoutSubmitFormOfferImport.update({
  id: '/submit-form/offer',
  path: '/submit-form/offer',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutScrapingApiUserAgentsRoute =
  LayoutScrapingApiUserAgentsImport.update({
    id: '/scraping-api/user-agents',
    path: '/scraping-api/user-agents',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutScrapingApiGoogleSerpRoute =
  LayoutScrapingApiGoogleSerpImport.update({
    id: '/scraping-api/google-serp',
    path: '/scraping-api/google-serp',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutScrapingApiExploreRoute = LayoutScrapingApiExploreImport.update({
  id: '/scraping-api/explore',
  path: '/scraping-api/explore',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutScrapingApiScrapingJobsIndexRoute =
  LayoutScrapingApiScrapingJobsIndexImport.update({
    id: '/scraping-api/scraping-jobs/',
    path: '/scraping-api/scraping-jobs/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutScrapingApiScrapingJobsJobIdRoute =
  LayoutScrapingApiScrapingJobsJobIdImport.update({
    id: '/scraping-api/scraping-jobs/$jobId',
    path: '/scraping-api/scraping-jobs/$jobId',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reformat-excel': {
      id: '/reformat-excel'
      path: '/reformat-excel'
      fullPath: '/reformat-excel'
      preLoaderRoute: typeof ReformatExcelImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/customers': {
      id: '/_layout/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof LayoutCustomersImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/file-explorer': {
      id: '/_layout/file-explorer'
      path: '/file-explorer'
      fullPath: '/file-explorer'
      preLoaderRoute: typeof LayoutFileExplorerImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/offers': {
      id: '/_layout/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof LayoutOffersImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/orders': {
      id: '/_layout/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof LayoutOrdersImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/submit-crop': {
      id: '/_layout/submit-crop'
      path: '/submit-crop'
      fullPath: '/submit-crop'
      preLoaderRoute: typeof LayoutSubmitCropImport
      parentRoute: typeof LayoutImport
    }
    '/progress/$jobId': {
      id: '/progress/$jobId'
      path: '/progress/$jobId'
      fullPath: '/progress/$jobId'
      preLoaderRoute: typeof ProgressJobIdImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/scraping-api/explore': {
      id: '/_layout/scraping-api/explore'
      path: '/scraping-api/explore'
      fullPath: '/scraping-api/explore'
      preLoaderRoute: typeof LayoutScrapingApiExploreImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/scraping-api/google-serp': {
      id: '/_layout/scraping-api/google-serp'
      path: '/scraping-api/google-serp'
      fullPath: '/scraping-api/google-serp'
      preLoaderRoute: typeof LayoutScrapingApiGoogleSerpImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/scraping-api/user-agents': {
      id: '/_layout/scraping-api/user-agents'
      path: '/scraping-api/user-agents'
      fullPath: '/scraping-api/user-agents'
      preLoaderRoute: typeof LayoutScrapingApiUserAgentsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/submit-form/offer': {
      id: '/_layout/submit-form/offer'
      path: '/submit-form/offer'
      fullPath: '/submit-form/offer'
      preLoaderRoute: typeof LayoutSubmitFormOfferImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/submit-form/success': {
      id: '/_layout/submit-form/success'
      path: '/submit-form/success'
      fullPath: '/submit-form/success'
      preLoaderRoute: typeof LayoutSubmitFormSuccessImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/tools/crop': {
      id: '/_layout/tools/crop'
      path: '/tools/crop'
      fullPath: '/tools/crop'
      preLoaderRoute: typeof LayoutToolsCropImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/tools/data-warehouse': {
      id: '/_layout/tools/data-warehouse'
      path: '/tools/data-warehouse'
      fullPath: '/tools/data-warehouse'
      preLoaderRoute: typeof LayoutToolsDataWarehouseImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/tools/google-images': {
      id: '/_layout/tools/google-images'
      path: '/tools/google-images'
      fullPath: '/tools/google-images'
      preLoaderRoute: typeof LayoutToolsGoogleImagesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/tools/image-links': {
      id: '/_layout/tools/image-links'
      path: '/tools/image-links'
      fullPath: '/tools/image-links'
      preLoaderRoute: typeof LayoutToolsImageLinksImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/scraping-api/scraping-jobs/$jobId': {
      id: '/_layout/scraping-api/scraping-jobs/$jobId'
      path: '/scraping-api/scraping-jobs/$jobId'
      fullPath: '/scraping-api/scraping-jobs/$jobId'
      preLoaderRoute: typeof LayoutScrapingApiScrapingJobsJobIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/scraping-api/scraping-jobs/': {
      id: '/_layout/scraping-api/scraping-jobs/'
      path: '/scraping-api/scraping-jobs'
      fullPath: '/scraping-api/scraping-jobs'
      preLoaderRoute: typeof LayoutScrapingApiScrapingJobsIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutCustomersRoute: typeof LayoutCustomersRoute
  LayoutFileExplorerRoute: typeof LayoutFileExplorerRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutOffersRoute: typeof LayoutOffersRoute
  LayoutOrdersRoute: typeof LayoutOrdersRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSubmitCropRoute: typeof LayoutSubmitCropRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutScrapingApiExploreRoute: typeof LayoutScrapingApiExploreRoute
  LayoutScrapingApiGoogleSerpRoute: typeof LayoutScrapingApiGoogleSerpRoute
  LayoutScrapingApiUserAgentsRoute: typeof LayoutScrapingApiUserAgentsRoute
  LayoutSubmitFormOfferRoute: typeof LayoutSubmitFormOfferRoute
  LayoutSubmitFormSuccessRoute: typeof LayoutSubmitFormSuccessRoute
  LayoutToolsCropRoute: typeof LayoutToolsCropRoute
  LayoutToolsDataWarehouseRoute: typeof LayoutToolsDataWarehouseRoute
  LayoutToolsGoogleImagesRoute: typeof LayoutToolsGoogleImagesRoute
  LayoutToolsImageLinksRoute: typeof LayoutToolsImageLinksRoute
  LayoutScrapingApiScrapingJobsJobIdRoute: typeof LayoutScrapingApiScrapingJobsJobIdRoute
  LayoutScrapingApiScrapingJobsIndexRoute: typeof LayoutScrapingApiScrapingJobsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutCustomersRoute: LayoutCustomersRoute,
  LayoutFileExplorerRoute: LayoutFileExplorerRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutOffersRoute: LayoutOffersRoute,
  LayoutOrdersRoute: LayoutOrdersRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSubmitCropRoute: LayoutSubmitCropRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutScrapingApiExploreRoute: LayoutScrapingApiExploreRoute,
  LayoutScrapingApiGoogleSerpRoute: LayoutScrapingApiGoogleSerpRoute,
  LayoutScrapingApiUserAgentsRoute: LayoutScrapingApiUserAgentsRoute,
  LayoutSubmitFormOfferRoute: LayoutSubmitFormOfferRoute,
  LayoutSubmitFormSuccessRoute: LayoutSubmitFormSuccessRoute,
  LayoutToolsCropRoute: LayoutToolsCropRoute,
  LayoutToolsDataWarehouseRoute: LayoutToolsDataWarehouseRoute,
  LayoutToolsGoogleImagesRoute: LayoutToolsGoogleImagesRoute,
  LayoutToolsImageLinksRoute: LayoutToolsImageLinksRoute,
  LayoutScrapingApiScrapingJobsJobIdRoute:
    LayoutScrapingApiScrapingJobsJobIdRoute,
  LayoutScrapingApiScrapingJobsIndexRoute:
    LayoutScrapingApiScrapingJobsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reformat-excel': typeof ReformatExcelRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/customers': typeof LayoutCustomersRoute
  '/file-explorer': typeof LayoutFileExplorerRoute
  '/items': typeof LayoutItemsRoute
  '/offers': typeof LayoutOffersRoute
  '/orders': typeof LayoutOrdersRoute
  '/settings': typeof LayoutSettingsRoute
  '/submit-crop': typeof LayoutSubmitCropRoute
  '/progress/$jobId': typeof ProgressJobIdRoute
  '/': typeof LayoutIndexRoute
  '/scraping-api/explore': typeof LayoutScrapingApiExploreRoute
  '/scraping-api/google-serp': typeof LayoutScrapingApiGoogleSerpRoute
  '/scraping-api/user-agents': typeof LayoutScrapingApiUserAgentsRoute
  '/submit-form/offer': typeof LayoutSubmitFormOfferRoute
  '/submit-form/success': typeof LayoutSubmitFormSuccessRoute
  '/tools/crop': typeof LayoutToolsCropRoute
  '/tools/data-warehouse': typeof LayoutToolsDataWarehouseRoute
  '/tools/google-images': typeof LayoutToolsGoogleImagesRoute
  '/tools/image-links': typeof LayoutToolsImageLinksRoute
  '/scraping-api/scraping-jobs/$jobId': typeof LayoutScrapingApiScrapingJobsJobIdRoute
  '/scraping-api/scraping-jobs': typeof LayoutScrapingApiScrapingJobsIndexRoute
}

export interface FileRoutesByTo {
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reformat-excel': typeof ReformatExcelRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/customers': typeof LayoutCustomersRoute
  '/file-explorer': typeof LayoutFileExplorerRoute
  '/items': typeof LayoutItemsRoute
  '/offers': typeof LayoutOffersRoute
  '/orders': typeof LayoutOrdersRoute
  '/settings': typeof LayoutSettingsRoute
  '/submit-crop': typeof LayoutSubmitCropRoute
  '/progress/$jobId': typeof ProgressJobIdRoute
  '/': typeof LayoutIndexRoute
  '/scraping-api/explore': typeof LayoutScrapingApiExploreRoute
  '/scraping-api/google-serp': typeof LayoutScrapingApiGoogleSerpRoute
  '/scraping-api/user-agents': typeof LayoutScrapingApiUserAgentsRoute
  '/submit-form/offer': typeof LayoutSubmitFormOfferRoute
  '/submit-form/success': typeof LayoutSubmitFormSuccessRoute
  '/tools/crop': typeof LayoutToolsCropRoute
  '/tools/data-warehouse': typeof LayoutToolsDataWarehouseRoute
  '/tools/google-images': typeof LayoutToolsGoogleImagesRoute
  '/tools/image-links': typeof LayoutToolsImageLinksRoute
  '/scraping-api/scraping-jobs/$jobId': typeof LayoutScrapingApiScrapingJobsJobIdRoute
  '/scraping-api/scraping-jobs': typeof LayoutScrapingApiScrapingJobsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reformat-excel': typeof ReformatExcelRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/customers': typeof LayoutCustomersRoute
  '/_layout/file-explorer': typeof LayoutFileExplorerRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/offers': typeof LayoutOffersRoute
  '/_layout/orders': typeof LayoutOrdersRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/submit-crop': typeof LayoutSubmitCropRoute
  '/progress/$jobId': typeof ProgressJobIdRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/scraping-api/explore': typeof LayoutScrapingApiExploreRoute
  '/_layout/scraping-api/google-serp': typeof LayoutScrapingApiGoogleSerpRoute
  '/_layout/scraping-api/user-agents': typeof LayoutScrapingApiUserAgentsRoute
  '/_layout/submit-form/offer': typeof LayoutSubmitFormOfferRoute
  '/_layout/submit-form/success': typeof LayoutSubmitFormSuccessRoute
  '/_layout/tools/crop': typeof LayoutToolsCropRoute
  '/_layout/tools/data-warehouse': typeof LayoutToolsDataWarehouseRoute
  '/_layout/tools/google-images': typeof LayoutToolsGoogleImagesRoute
  '/_layout/tools/image-links': typeof LayoutToolsImageLinksRoute
  '/_layout/scraping-api/scraping-jobs/$jobId': typeof LayoutScrapingApiScrapingJobsJobIdRoute
  '/_layout/scraping-api/scraping-jobs/': typeof LayoutScrapingApiScrapingJobsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/insights'
    | '/login'
    | '/recover-password'
    | '/reformat-excel'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/customers'
    | '/file-explorer'
    | '/items'
    | '/offers'
    | '/orders'
    | '/settings'
    | '/submit-crop'
    | '/progress/$jobId'
    | '/'
    | '/scraping-api/explore'
    | '/scraping-api/google-serp'
    | '/scraping-api/user-agents'
    | '/submit-form/offer'
    | '/submit-form/success'
    | '/tools/crop'
    | '/tools/data-warehouse'
    | '/tools/google-images'
    | '/tools/image-links'
    | '/scraping-api/scraping-jobs/$jobId'
    | '/scraping-api/scraping-jobs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/insights'
    | '/login'
    | '/recover-password'
    | '/reformat-excel'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/customers'
    | '/file-explorer'
    | '/items'
    | '/offers'
    | '/orders'
    | '/settings'
    | '/submit-crop'
    | '/progress/$jobId'
    | '/'
    | '/scraping-api/explore'
    | '/scraping-api/google-serp'
    | '/scraping-api/user-agents'
    | '/submit-form/offer'
    | '/submit-form/success'
    | '/tools/crop'
    | '/tools/data-warehouse'
    | '/tools/google-images'
    | '/tools/image-links'
    | '/scraping-api/scraping-jobs/$jobId'
    | '/scraping-api/scraping-jobs'
  id:
    | '__root__'
    | '/_layout'
    | '/insights'
    | '/login'
    | '/recover-password'
    | '/reformat-excel'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/customers'
    | '/_layout/file-explorer'
    | '/_layout/items'
    | '/_layout/offers'
    | '/_layout/orders'
    | '/_layout/settings'
    | '/_layout/submit-crop'
    | '/progress/$jobId'
    | '/_layout/'
    | '/_layout/scraping-api/explore'
    | '/_layout/scraping-api/google-serp'
    | '/_layout/scraping-api/user-agents'
    | '/_layout/submit-form/offer'
    | '/_layout/submit-form/success'
    | '/_layout/tools/crop'
    | '/_layout/tools/data-warehouse'
    | '/_layout/tools/google-images'
    | '/_layout/tools/image-links'
    | '/_layout/scraping-api/scraping-jobs/$jobId'
    | '/_layout/scraping-api/scraping-jobs/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ReformatExcelRoute: typeof ReformatExcelRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ProgressJobIdRoute: typeof ProgressJobIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ReformatExcelRoute: ReformatExcelRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ProgressJobIdRoute: ProgressJobIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/insights",
        "/login",
        "/recover-password",
        "/reformat-excel",
        "/reset-password",
        "/signup",
        "/progress/$jobId"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/admin",
        "/_layout/customers",
        "/_layout/file-explorer",
        "/_layout/items",
        "/_layout/offers",
        "/_layout/orders",
        "/_layout/settings",
        "/_layout/submit-crop",
        "/_layout/",
        "/_layout/scraping-api/explore",
        "/_layout/scraping-api/google-serp",
        "/_layout/scraping-api/user-agents",
        "/_layout/submit-form/offer",
        "/_layout/submit-form/success",
        "/_layout/tools/crop",
        "/_layout/tools/data-warehouse",
        "/_layout/tools/google-images",
        "/_layout/tools/image-links",
        "/_layout/scraping-api/scraping-jobs/$jobId",
        "/_layout/scraping-api/scraping-jobs/"
      ]
    },
    "/insights": {
      "filePath": "insights.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/recover-password": {
      "filePath": "recover-password.tsx"
    },
    "/reformat-excel": {
      "filePath": "reformat-excel.tsx"
    },
    "/reset-password": {
      "filePath": "reset-password.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_layout/admin": {
      "filePath": "_layout/admin.tsx",
      "parent": "/_layout"
    },
    "/_layout/customers": {
      "filePath": "_layout/customers.tsx",
      "parent": "/_layout"
    },
    "/_layout/file-explorer": {
      "filePath": "_layout/file-explorer.tsx",
      "parent": "/_layout"
    },
    "/_layout/items": {
      "filePath": "_layout/items.tsx",
      "parent": "/_layout"
    },
    "/_layout/offers": {
      "filePath": "_layout/offers.tsx",
      "parent": "/_layout"
    },
    "/_layout/orders": {
      "filePath": "_layout/orders.tsx",
      "parent": "/_layout"
    },
    "/_layout/settings": {
      "filePath": "_layout/settings.tsx",
      "parent": "/_layout"
    },
    "/_layout/submit-crop": {
      "filePath": "_layout/submit-crop.tsx",
      "parent": "/_layout"
    },
    "/progress/$jobId": {
      "filePath": "progress/$jobId.tsx"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/scraping-api/explore": {
      "filePath": "_layout/scraping-api/explore.tsx",
      "parent": "/_layout"
    },
    "/_layout/scraping-api/google-serp": {
      "filePath": "_layout/scraping-api/google-serp.tsx",
      "parent": "/_layout"
    },
    "/_layout/scraping-api/user-agents": {
      "filePath": "_layout/scraping-api/user-agents.tsx",
      "parent": "/_layout"
    },
    "/_layout/submit-form/offer": {
      "filePath": "_layout/submit-form/offer.tsx",
      "parent": "/_layout"
    },
    "/_layout/submit-form/success": {
      "filePath": "_layout/submit-form/success.tsx",
      "parent": "/_layout"
    },
    "/_layout/tools/crop": {
      "filePath": "_layout/tools/crop.tsx",
      "parent": "/_layout"
    },
    "/_layout/tools/data-warehouse": {
      "filePath": "_layout/tools/data-warehouse.tsx",
      "parent": "/_layout"
    },
    "/_layout/tools/google-images": {
      "filePath": "_layout/tools/google-images.tsx",
      "parent": "/_layout"
    },
    "/_layout/tools/image-links": {
      "filePath": "_layout/tools/image-links.tsx",
      "parent": "/_layout"
    },
    "/_layout/scraping-api/scraping-jobs/$jobId": {
      "filePath": "_layout/scraping-api/scraping-jobs/$jobId.tsx",
      "parent": "/_layout"
    },
    "/_layout/scraping-api/scraping-jobs/": {
      "filePath": "_layout/scraping-api/scraping-jobs/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
