/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as ReformatExcelImport } from './routes/reformat-excel'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as GoogleSerpCmsImport } from './routes/google-serp-cms'
import { Route as CmsImport } from './routes/cms'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as ProgressJobIdImport } from './routes/progress/$jobId'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutFileExplorerImport } from './routes/_layout/file-explorer'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as PublicToolsImageLinksImport } from './routes/public/tools/image-links'
import { Route as PublicToolsGoogleImagesImport } from './routes/public/tools/google-images'
import { Route as PublicToolsDataWarehouseImport } from './routes/public/tools/data-warehouse'
import { Route as PublicToolsCropImport } from './routes/public/tools/crop'
import { Route as LayoutScrapingApiJobsImport } from './routes/_layout/scraping-api/jobs'
import { Route as LayoutScrapingApiInsightsImport } from './routes/_layout/scraping-api/insights'
import { Route as LayoutToolsImageLinksIndexImport } from './routes/_layout/tools/image-links/index'
import { Route as LayoutToolsGoogleImagesIndexImport } from './routes/_layout/tools/google-images/index'
import { Route as LayoutToolsDataWarehouseIndexImport } from './routes/_layout/tools/data-warehouse/index'
import { Route as LayoutToolsCropIndexImport } from './routes/_layout/tools/crop/index'
import { Route as LayoutToolsImageLinksUploadImport } from './routes/_layout/tools/image-links/upload'
import { Route as LayoutToolsGoogleImagesUploadImport } from './routes/_layout/tools/google-images/upload'
import { Route as LayoutToolsDataWarehouseUploadImport } from './routes/_layout/tools/data-warehouse/upload'
import { Route as LayoutToolsCropUploadImport } from './routes/_layout/tools/crop/upload'
import { Route as LayoutScrapingApiScrapingJobsJobIdImport } from './routes/_layout/scraping-api/scraping-jobs/$jobId'
import { Route as LayoutScrapingApiScrapingJobsLegacyJobIdImport } from './routes/_layout/scraping-api/scraping-jobs/legacy/$jobId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const ReformatExcelRoute = ReformatExcelImport.update({
  id: '/reformat-excel',
  path: '/reformat-excel',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const GoogleSerpCmsRoute = GoogleSerpCmsImport.update({
  id: '/google-serp-cms',
  path: '/google-serp-cms',
  getParentRoute: () => rootRoute,
} as any)

const CmsRoute = CmsImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const ProgressJobIdRoute = ProgressJobIdImport.update({
  id: '/progress/$jobId',
  path: '/progress/$jobId',
  getParentRoute: () => rootRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutFileExplorerRoute = LayoutFileExplorerImport.update({
  id: '/file-explorer',
  path: '/file-explorer',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const PublicToolsImageLinksRoute = PublicToolsImageLinksImport.update({
  id: '/public/tools/image-links',
  path: '/public/tools/image-links',
  getParentRoute: () => rootRoute,
} as any)

const PublicToolsGoogleImagesRoute = PublicToolsGoogleImagesImport.update({
  id: '/public/tools/google-images',
  path: '/public/tools/google-images',
  getParentRoute: () => rootRoute,
} as any)

const PublicToolsDataWarehouseRoute = PublicToolsDataWarehouseImport.update({
  id: '/public/tools/data-warehouse',
  path: '/public/tools/data-warehouse',
  getParentRoute: () => rootRoute,
} as any)

const PublicToolsCropRoute = PublicToolsCropImport.update({
  id: '/public/tools/crop',
  path: '/public/tools/crop',
  getParentRoute: () => rootRoute,
} as any)

const LayoutScrapingApiJobsRoute = LayoutScrapingApiJobsImport.update({
  id: '/scraping-api/jobs',
  path: '/scraping-api/jobs',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutScrapingApiInsightsRoute = LayoutScrapingApiInsightsImport.update({
  id: '/scraping-api/insights',
  path: '/scraping-api/insights',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutToolsImageLinksIndexRoute = LayoutToolsImageLinksIndexImport.update(
  {
    id: '/tools/image-links/',
    path: '/tools/image-links/',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutToolsGoogleImagesIndexRoute =
  LayoutToolsGoogleImagesIndexImport.update({
    id: '/tools/google-images/',
    path: '/tools/google-images/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutToolsDataWarehouseIndexRoute =
  LayoutToolsDataWarehouseIndexImport.update({
    id: '/tools/data-warehouse/',
    path: '/tools/data-warehouse/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutToolsCropIndexRoute = LayoutToolsCropIndexImport.update({
  id: '/tools/crop/',
  path: '/tools/crop/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutToolsImageLinksUploadRoute =
  LayoutToolsImageLinksUploadImport.update({
    id: '/tools/image-links/upload',
    path: '/tools/image-links/upload',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutToolsGoogleImagesUploadRoute =
  LayoutToolsGoogleImagesUploadImport.update({
    id: '/tools/google-images/upload',
    path: '/tools/google-images/upload',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutToolsDataWarehouseUploadRoute =
  LayoutToolsDataWarehouseUploadImport.update({
    id: '/tools/data-warehouse/upload',
    path: '/tools/data-warehouse/upload',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutToolsCropUploadRoute = LayoutToolsCropUploadImport.update({
  id: '/tools/crop/upload',
  path: '/tools/crop/upload',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutScrapingApiScrapingJobsJobIdRoute =
  LayoutScrapingApiScrapingJobsJobIdImport.update({
    id: '/scraping-api/scraping-jobs/$jobId',
    path: '/scraping-api/scraping-jobs/$jobId',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutScrapingApiScrapingJobsLegacyJobIdRoute =
  LayoutScrapingApiScrapingJobsLegacyJobIdImport.update({
    id: '/scraping-api/scraping-jobs/legacy/$jobId',
    path: '/scraping-api/scraping-jobs/legacy/$jobId',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/cms': {
      id: '/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsImport
      parentRoute: typeof rootRoute
    }
    '/google-serp-cms': {
      id: '/google-serp-cms'
      path: '/google-serp-cms'
      fullPath: '/google-serp-cms'
      preLoaderRoute: typeof GoogleSerpCmsImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reformat-excel': {
      id: '/reformat-excel'
      path: '/reformat-excel'
      fullPath: '/reformat-excel'
      preLoaderRoute: typeof ReformatExcelImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/file-explorer': {
      id: '/_layout/file-explorer'
      path: '/file-explorer'
      fullPath: '/file-explorer'
      preLoaderRoute: typeof LayoutFileExplorerImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/progress/$jobId': {
      id: '/progress/$jobId'
      path: '/progress/$jobId'
      fullPath: '/progress/$jobId'
      preLoaderRoute: typeof ProgressJobIdImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/scraping-api/insights': {
      id: '/_layout/scraping-api/insights'
      path: '/scraping-api/insights'
      fullPath: '/scraping-api/insights'
      preLoaderRoute: typeof LayoutScrapingApiInsightsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/scraping-api/jobs': {
      id: '/_layout/scraping-api/jobs'
      path: '/scraping-api/jobs'
      fullPath: '/scraping-api/jobs'
      preLoaderRoute: typeof LayoutScrapingApiJobsImport
      parentRoute: typeof LayoutImport
    }
    '/public/tools/crop': {
      id: '/public/tools/crop'
      path: '/public/tools/crop'
      fullPath: '/public/tools/crop'
      preLoaderRoute: typeof PublicToolsCropImport
      parentRoute: typeof rootRoute
    }
    '/public/tools/data-warehouse': {
      id: '/public/tools/data-warehouse'
      path: '/public/tools/data-warehouse'
      fullPath: '/public/tools/data-warehouse'
      preLoaderRoute: typeof PublicToolsDataWarehouseImport
      parentRoute: typeof rootRoute
    }
    '/public/tools/google-images': {
      id: '/public/tools/google-images'
      path: '/public/tools/google-images'
      fullPath: '/public/tools/google-images'
      preLoaderRoute: typeof PublicToolsGoogleImagesImport
      parentRoute: typeof rootRoute
    }
    '/public/tools/image-links': {
      id: '/public/tools/image-links'
      path: '/public/tools/image-links'
      fullPath: '/public/tools/image-links'
      preLoaderRoute: typeof PublicToolsImageLinksImport
      parentRoute: typeof rootRoute
    }
    '/_layout/scraping-api/scraping-jobs/$jobId': {
      id: '/_layout/scraping-api/scraping-jobs/$jobId'
      path: '/scraping-api/scraping-jobs/$jobId'
      fullPath: '/scraping-api/scraping-jobs/$jobId'
      preLoaderRoute: typeof LayoutScrapingApiScrapingJobsJobIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/tools/crop/upload': {
      id: '/_layout/tools/crop/upload'
      path: '/tools/crop/upload'
      fullPath: '/tools/crop/upload'
      preLoaderRoute: typeof LayoutToolsCropUploadImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/tools/data-warehouse/upload': {
      id: '/_layout/tools/data-warehouse/upload'
      path: '/tools/data-warehouse/upload'
      fullPath: '/tools/data-warehouse/upload'
      preLoaderRoute: typeof LayoutToolsDataWarehouseUploadImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/tools/google-images/upload': {
      id: '/_layout/tools/google-images/upload'
      path: '/tools/google-images/upload'
      fullPath: '/tools/google-images/upload'
      preLoaderRoute: typeof LayoutToolsGoogleImagesUploadImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/tools/image-links/upload': {
      id: '/_layout/tools/image-links/upload'
      path: '/tools/image-links/upload'
      fullPath: '/tools/image-links/upload'
      preLoaderRoute: typeof LayoutToolsImageLinksUploadImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/tools/crop/': {
      id: '/_layout/tools/crop/'
      path: '/tools/crop'
      fullPath: '/tools/crop'
      preLoaderRoute: typeof LayoutToolsCropIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/tools/data-warehouse/': {
      id: '/_layout/tools/data-warehouse/'
      path: '/tools/data-warehouse'
      fullPath: '/tools/data-warehouse'
      preLoaderRoute: typeof LayoutToolsDataWarehouseIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/tools/google-images/': {
      id: '/_layout/tools/google-images/'
      path: '/tools/google-images'
      fullPath: '/tools/google-images'
      preLoaderRoute: typeof LayoutToolsGoogleImagesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/tools/image-links/': {
      id: '/_layout/tools/image-links/'
      path: '/tools/image-links'
      fullPath: '/tools/image-links'
      preLoaderRoute: typeof LayoutToolsImageLinksIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/scraping-api/scraping-jobs/legacy/$jobId': {
      id: '/_layout/scraping-api/scraping-jobs/legacy/$jobId'
      path: '/scraping-api/scraping-jobs/legacy/$jobId'
      fullPath: '/scraping-api/scraping-jobs/legacy/$jobId'
      preLoaderRoute: typeof LayoutScrapingApiScrapingJobsLegacyJobIdImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutFileExplorerRoute: typeof LayoutFileExplorerRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutScrapingApiInsightsRoute: typeof LayoutScrapingApiInsightsRoute
  LayoutScrapingApiJobsRoute: typeof LayoutScrapingApiJobsRoute
  LayoutScrapingApiScrapingJobsJobIdRoute: typeof LayoutScrapingApiScrapingJobsJobIdRoute
  LayoutToolsCropUploadRoute: typeof LayoutToolsCropUploadRoute
  LayoutToolsDataWarehouseUploadRoute: typeof LayoutToolsDataWarehouseUploadRoute
  LayoutToolsGoogleImagesUploadRoute: typeof LayoutToolsGoogleImagesUploadRoute
  LayoutToolsImageLinksUploadRoute: typeof LayoutToolsImageLinksUploadRoute
  LayoutToolsCropIndexRoute: typeof LayoutToolsCropIndexRoute
  LayoutToolsDataWarehouseIndexRoute: typeof LayoutToolsDataWarehouseIndexRoute
  LayoutToolsGoogleImagesIndexRoute: typeof LayoutToolsGoogleImagesIndexRoute
  LayoutToolsImageLinksIndexRoute: typeof LayoutToolsImageLinksIndexRoute
  LayoutScrapingApiScrapingJobsLegacyJobIdRoute: typeof LayoutScrapingApiScrapingJobsLegacyJobIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutFileExplorerRoute: LayoutFileExplorerRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutScrapingApiInsightsRoute: LayoutScrapingApiInsightsRoute,
  LayoutScrapingApiJobsRoute: LayoutScrapingApiJobsRoute,
  LayoutScrapingApiScrapingJobsJobIdRoute:
    LayoutScrapingApiScrapingJobsJobIdRoute,
  LayoutToolsCropUploadRoute: LayoutToolsCropUploadRoute,
  LayoutToolsDataWarehouseUploadRoute: LayoutToolsDataWarehouseUploadRoute,
  LayoutToolsGoogleImagesUploadRoute: LayoutToolsGoogleImagesUploadRoute,
  LayoutToolsImageLinksUploadRoute: LayoutToolsImageLinksUploadRoute,
  LayoutToolsCropIndexRoute: LayoutToolsCropIndexRoute,
  LayoutToolsDataWarehouseIndexRoute: LayoutToolsDataWarehouseIndexRoute,
  LayoutToolsGoogleImagesIndexRoute: LayoutToolsGoogleImagesIndexRoute,
  LayoutToolsImageLinksIndexRoute: LayoutToolsImageLinksIndexRoute,
  LayoutScrapingApiScrapingJobsLegacyJobIdRoute:
    LayoutScrapingApiScrapingJobsLegacyJobIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/cms': typeof CmsRoute
  '/google-serp-cms': typeof GoogleSerpCmsRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reformat-excel': typeof ReformatExcelRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/file-explorer': typeof LayoutFileExplorerRoute
  '/settings': typeof LayoutSettingsRoute
  '/progress/$jobId': typeof ProgressJobIdRoute
  '/': typeof LayoutIndexRoute
  '/scraping-api/insights': typeof LayoutScrapingApiInsightsRoute
  '/scraping-api/jobs': typeof LayoutScrapingApiJobsRoute
  '/public/tools/crop': typeof PublicToolsCropRoute
  '/public/tools/data-warehouse': typeof PublicToolsDataWarehouseRoute
  '/public/tools/google-images': typeof PublicToolsGoogleImagesRoute
  '/public/tools/image-links': typeof PublicToolsImageLinksRoute
  '/scraping-api/scraping-jobs/$jobId': typeof LayoutScrapingApiScrapingJobsJobIdRoute
  '/tools/crop/upload': typeof LayoutToolsCropUploadRoute
  '/tools/data-warehouse/upload': typeof LayoutToolsDataWarehouseUploadRoute
  '/tools/google-images/upload': typeof LayoutToolsGoogleImagesUploadRoute
  '/tools/image-links/upload': typeof LayoutToolsImageLinksUploadRoute
  '/tools/crop': typeof LayoutToolsCropIndexRoute
  '/tools/data-warehouse': typeof LayoutToolsDataWarehouseIndexRoute
  '/tools/google-images': typeof LayoutToolsGoogleImagesIndexRoute
  '/tools/image-links': typeof LayoutToolsImageLinksIndexRoute
  '/scraping-api/scraping-jobs/legacy/$jobId': typeof LayoutScrapingApiScrapingJobsLegacyJobIdRoute
}

export interface FileRoutesByTo {
  '/cms': typeof CmsRoute
  '/google-serp-cms': typeof GoogleSerpCmsRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reformat-excel': typeof ReformatExcelRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/file-explorer': typeof LayoutFileExplorerRoute
  '/settings': typeof LayoutSettingsRoute
  '/progress/$jobId': typeof ProgressJobIdRoute
  '/': typeof LayoutIndexRoute
  '/scraping-api/insights': typeof LayoutScrapingApiInsightsRoute
  '/scraping-api/jobs': typeof LayoutScrapingApiJobsRoute
  '/public/tools/crop': typeof PublicToolsCropRoute
  '/public/tools/data-warehouse': typeof PublicToolsDataWarehouseRoute
  '/public/tools/google-images': typeof PublicToolsGoogleImagesRoute
  '/public/tools/image-links': typeof PublicToolsImageLinksRoute
  '/scraping-api/scraping-jobs/$jobId': typeof LayoutScrapingApiScrapingJobsJobIdRoute
  '/tools/crop/upload': typeof LayoutToolsCropUploadRoute
  '/tools/data-warehouse/upload': typeof LayoutToolsDataWarehouseUploadRoute
  '/tools/google-images/upload': typeof LayoutToolsGoogleImagesUploadRoute
  '/tools/image-links/upload': typeof LayoutToolsImageLinksUploadRoute
  '/tools/crop': typeof LayoutToolsCropIndexRoute
  '/tools/data-warehouse': typeof LayoutToolsDataWarehouseIndexRoute
  '/tools/google-images': typeof LayoutToolsGoogleImagesIndexRoute
  '/tools/image-links': typeof LayoutToolsImageLinksIndexRoute
  '/scraping-api/scraping-jobs/legacy/$jobId': typeof LayoutScrapingApiScrapingJobsLegacyJobIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/cms': typeof CmsRoute
  '/google-serp-cms': typeof GoogleSerpCmsRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reformat-excel': typeof ReformatExcelRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/file-explorer': typeof LayoutFileExplorerRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/progress/$jobId': typeof ProgressJobIdRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/scraping-api/insights': typeof LayoutScrapingApiInsightsRoute
  '/_layout/scraping-api/jobs': typeof LayoutScrapingApiJobsRoute
  '/public/tools/crop': typeof PublicToolsCropRoute
  '/public/tools/data-warehouse': typeof PublicToolsDataWarehouseRoute
  '/public/tools/google-images': typeof PublicToolsGoogleImagesRoute
  '/public/tools/image-links': typeof PublicToolsImageLinksRoute
  '/_layout/scraping-api/scraping-jobs/$jobId': typeof LayoutScrapingApiScrapingJobsJobIdRoute
  '/_layout/tools/crop/upload': typeof LayoutToolsCropUploadRoute
  '/_layout/tools/data-warehouse/upload': typeof LayoutToolsDataWarehouseUploadRoute
  '/_layout/tools/google-images/upload': typeof LayoutToolsGoogleImagesUploadRoute
  '/_layout/tools/image-links/upload': typeof LayoutToolsImageLinksUploadRoute
  '/_layout/tools/crop/': typeof LayoutToolsCropIndexRoute
  '/_layout/tools/data-warehouse/': typeof LayoutToolsDataWarehouseIndexRoute
  '/_layout/tools/google-images/': typeof LayoutToolsGoogleImagesIndexRoute
  '/_layout/tools/image-links/': typeof LayoutToolsImageLinksIndexRoute
  '/_layout/scraping-api/scraping-jobs/legacy/$jobId': typeof LayoutScrapingApiScrapingJobsLegacyJobIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/cms'
    | '/google-serp-cms'
    | '/login'
    | '/recover-password'
    | '/reformat-excel'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/file-explorer'
    | '/settings'
    | '/progress/$jobId'
    | '/'
    | '/scraping-api/insights'
    | '/scraping-api/jobs'
    | '/public/tools/crop'
    | '/public/tools/data-warehouse'
    | '/public/tools/google-images'
    | '/public/tools/image-links'
    | '/scraping-api/scraping-jobs/$jobId'
    | '/tools/crop/upload'
    | '/tools/data-warehouse/upload'
    | '/tools/google-images/upload'
    | '/tools/image-links/upload'
    | '/tools/crop'
    | '/tools/data-warehouse'
    | '/tools/google-images'
    | '/tools/image-links'
    | '/scraping-api/scraping-jobs/legacy/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cms'
    | '/google-serp-cms'
    | '/login'
    | '/recover-password'
    | '/reformat-excel'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/file-explorer'
    | '/settings'
    | '/progress/$jobId'
    | '/'
    | '/scraping-api/insights'
    | '/scraping-api/jobs'
    | '/public/tools/crop'
    | '/public/tools/data-warehouse'
    | '/public/tools/google-images'
    | '/public/tools/image-links'
    | '/scraping-api/scraping-jobs/$jobId'
    | '/tools/crop/upload'
    | '/tools/data-warehouse/upload'
    | '/tools/google-images/upload'
    | '/tools/image-links/upload'
    | '/tools/crop'
    | '/tools/data-warehouse'
    | '/tools/google-images'
    | '/tools/image-links'
    | '/scraping-api/scraping-jobs/legacy/$jobId'
  id:
    | '__root__'
    | '/_layout'
    | '/cms'
    | '/google-serp-cms'
    | '/login'
    | '/recover-password'
    | '/reformat-excel'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/file-explorer'
    | '/_layout/settings'
    | '/progress/$jobId'
    | '/_layout/'
    | '/_layout/scraping-api/insights'
    | '/_layout/scraping-api/jobs'
    | '/public/tools/crop'
    | '/public/tools/data-warehouse'
    | '/public/tools/google-images'
    | '/public/tools/image-links'
    | '/_layout/scraping-api/scraping-jobs/$jobId'
    | '/_layout/tools/crop/upload'
    | '/_layout/tools/data-warehouse/upload'
    | '/_layout/tools/google-images/upload'
    | '/_layout/tools/image-links/upload'
    | '/_layout/tools/crop/'
    | '/_layout/tools/data-warehouse/'
    | '/_layout/tools/google-images/'
    | '/_layout/tools/image-links/'
    | '/_layout/scraping-api/scraping-jobs/legacy/$jobId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  CmsRoute: typeof CmsRoute
  GoogleSerpCmsRoute: typeof GoogleSerpCmsRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ReformatExcelRoute: typeof ReformatExcelRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ProgressJobIdRoute: typeof ProgressJobIdRoute
  PublicToolsCropRoute: typeof PublicToolsCropRoute
  PublicToolsDataWarehouseRoute: typeof PublicToolsDataWarehouseRoute
  PublicToolsGoogleImagesRoute: typeof PublicToolsGoogleImagesRoute
  PublicToolsImageLinksRoute: typeof PublicToolsImageLinksRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  CmsRoute: CmsRoute,
  GoogleSerpCmsRoute: GoogleSerpCmsRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ReformatExcelRoute: ReformatExcelRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ProgressJobIdRoute: ProgressJobIdRoute,
  PublicToolsCropRoute: PublicToolsCropRoute,
  PublicToolsDataWarehouseRoute: PublicToolsDataWarehouseRoute,
  PublicToolsGoogleImagesRoute: PublicToolsGoogleImagesRoute,
  PublicToolsImageLinksRoute: PublicToolsImageLinksRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/cms",
        "/google-serp-cms",
        "/login",
        "/recover-password",
        "/reformat-excel",
        "/reset-password",
        "/signup",
        "/progress/$jobId",
        "/public/tools/crop",
        "/public/tools/data-warehouse",
        "/public/tools/google-images",
        "/public/tools/image-links"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/admin",
        "/_layout/file-explorer",
        "/_layout/settings",
        "/_layout/",
        "/_layout/scraping-api/insights",
        "/_layout/scraping-api/jobs",
        "/_layout/scraping-api/scraping-jobs/$jobId",
        "/_layout/tools/crop/upload",
        "/_layout/tools/data-warehouse/upload",
        "/_layout/tools/google-images/upload",
        "/_layout/tools/image-links/upload",
        "/_layout/tools/crop/",
        "/_layout/tools/data-warehouse/",
        "/_layout/tools/google-images/",
        "/_layout/tools/image-links/",
        "/_layout/scraping-api/scraping-jobs/legacy/$jobId"
      ]
    },
    "/cms": {
      "filePath": "cms.tsx"
    },
    "/google-serp-cms": {
      "filePath": "google-serp-cms.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/recover-password": {
      "filePath": "recover-password.tsx"
    },
    "/reformat-excel": {
      "filePath": "reformat-excel.tsx"
    },
    "/reset-password": {
      "filePath": "reset-password.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_layout/admin": {
      "filePath": "_layout/admin.tsx",
      "parent": "/_layout"
    },
    "/_layout/file-explorer": {
      "filePath": "_layout/file-explorer.tsx",
      "parent": "/_layout"
    },
    "/_layout/settings": {
      "filePath": "_layout/settings.tsx",
      "parent": "/_layout"
    },
    "/progress/$jobId": {
      "filePath": "progress/$jobId.tsx"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/scraping-api/insights": {
      "filePath": "_layout/scraping-api/insights.tsx",
      "parent": "/_layout"
    },
    "/_layout/scraping-api/jobs": {
      "filePath": "_layout/scraping-api/jobs.tsx",
      "parent": "/_layout"
    },
    "/public/tools/crop": {
      "filePath": "public/tools/crop.tsx"
    },
    "/public/tools/data-warehouse": {
      "filePath": "public/tools/data-warehouse.tsx"
    },
    "/public/tools/google-images": {
      "filePath": "public/tools/google-images.tsx"
    },
    "/public/tools/image-links": {
      "filePath": "public/tools/image-links.tsx"
    },
    "/_layout/scraping-api/scraping-jobs/$jobId": {
      "filePath": "_layout/scraping-api/scraping-jobs/$jobId.tsx",
      "parent": "/_layout"
    },
    "/_layout/tools/crop/upload": {
      "filePath": "_layout/tools/crop/upload.tsx",
      "parent": "/_layout"
    },
    "/_layout/tools/data-warehouse/upload": {
      "filePath": "_layout/tools/data-warehouse/upload.tsx",
      "parent": "/_layout"
    },
    "/_layout/tools/google-images/upload": {
      "filePath": "_layout/tools/google-images/upload.tsx",
      "parent": "/_layout"
    },
    "/_layout/tools/image-links/upload": {
      "filePath": "_layout/tools/image-links/upload.tsx",
      "parent": "/_layout"
    },
    "/_layout/tools/crop/": {
      "filePath": "_layout/tools/crop/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/tools/data-warehouse/": {
      "filePath": "_layout/tools/data-warehouse/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/tools/google-images/": {
      "filePath": "_layout/tools/google-images/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/tools/image-links/": {
      "filePath": "_layout/tools/image-links/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/scraping-api/scraping-jobs/legacy/$jobId": {
      "filePath": "_layout/scraping-api/scraping-jobs/legacy/$jobId.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
